--------------------------------------------------------
--  Arquivo criado - sexta-feira-novembro-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_LINK
--------------------------------------------------------

   CREATE SEQUENCE  "BLANK"."SQ_LINK"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_NOTICIA
--------------------------------------------------------

   CREATE SEQUENCE  "BLANK"."SQ_NOTICIA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DOMINIO
--------------------------------------------------------

  CREATE TABLE "BLANK"."DOMINIO" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TP_DOMINIO" VARCHAR2(255 BYTE), 
	"NM_DOMINIO" VARCHAR2(255 BYTE), 
	"DS_DOMINIO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Table LINK
--------------------------------------------------------

  CREATE TABLE "BLANK"."LINK" 
   (	"ID" NUMBER, 
	"DS_TITULO" VARCHAR2(255 BYTE), 
	"DS_URL" VARCHAR2(1000 BYTE), 
	"DT_CRIACAO" DATE, 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Table NOTICIA
--------------------------------------------------------

  CREATE TABLE "BLANK"."NOTICIA" 
   (	"ID" NUMBER, 
	"DS_TITULO" VARCHAR2(255 BYTE), 
	"DS_NOTICIA" VARCHAR2(2000 BYTE), 
	"DT_CRIACAO" DATE, 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Table PARAMETRO
--------------------------------------------------------

  CREATE TABLE "BLANK"."PARAMETRO" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"DS_URL_SEGURANCA_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_ENTIDADE_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_LOG_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_EMAIL_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_FONETICA_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_ASSINATURA_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_DIPLOMA_TRE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLANK"."PK_NOTICIA" ON "BLANK"."NOTICIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Index PK_PARAMETRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLANK"."PK_PARAMETRO" ON "BLANK"."PARAMETRO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  DDL for Index PK_LINK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLANK"."PK_LINK" ON "BLANK"."LINK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK" ;
--------------------------------------------------------
--  Constraints for Table DOMINIO
--------------------------------------------------------

  ALTER TABLE "BLANK"."DOMINIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."DOMINIO" MODIFY ("TP_DOMINIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARAMETRO
--------------------------------------------------------

  ALTER TABLE "BLANK"."PARAMETRO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."PARAMETRO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."PARAMETRO" ADD CONSTRAINT "PK_PARAMETRO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTICIA
--------------------------------------------------------

  ALTER TABLE "BLANK"."NOTICIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."NOTICIA" MODIFY ("DS_TITULO" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."NOTICIA" MODIFY ("DS_NOTICIA" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."NOTICIA" MODIFY ("DT_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."NOTICIA" ADD CONSTRAINT "CK_NOTICIA_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "BLANK"."NOTICIA" ADD CONSTRAINT "PK_NOTICIA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LINK
--------------------------------------------------------

  ALTER TABLE "BLANK"."LINK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."LINK" MODIFY ("DS_TITULO" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."LINK" MODIFY ("DS_URL" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."LINK" MODIFY ("DT_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "BLANK"."LINK" ADD CONSTRAINT "CK_LINK_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "BLANK"."LINK" ADD CONSTRAINT "PK_LINK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLANK"  ENABLE;
