--------------------------------------------------------
--  Arquivo criado - sexta-feira-novembro-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type AR_ID_NUMBER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PANDORA"."AR_ID_NUMBER" AS TABLE OF NUMBER;

/
--------------------------------------------------------
--  DDL for Type AR_ID_STRING
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "PANDORA"."AR_ID_STRING" AS TABLE OF VARCHAR2(40);

/
--------------------------------------------------------
--  DDL for Sequence SQ_ERRO
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_ERRO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_ESQUEMA
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_ESQUEMA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_FUNCIONALIDADE
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_FUNCIONALIDADE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_GRUPO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_HOST
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_HOST"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_INSTALACAO
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_INSTALACAO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_LINK
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_LINK"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_LOG
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_LOG"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_NOTICIA
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_NOTICIA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_PERFIL
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_PERFIL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_SERVICO
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_SERVICO"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_SISTEMA
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_SISTEMA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_TECNOLOGIA_SISTEMA
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_TECNOLOGIA_SISTEMA"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_TIPO_FUNCIONALIDADE
--------------------------------------------------------

   CREATE SEQUENCE  "PANDORA"."SQ_TIPO_FUNCIONALIDADE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table DOMINIO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."DOMINIO" 
   (	"ID" VARCHAR2(50 BYTE), 
	"TP_DOMINIO" VARCHAR2(255 BYTE), 
	"NM_DOMINIO" VARCHAR2(255 BYTE), 
	"DS_DOMINIO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table ERRO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."ERRO" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"NM_LOGIN" VARCHAR2(20 BYTE), 
	"NR_MATRICULA" VARCHAR2(8 BYTE), 
	"ID_UNIDADE" NUMBER(5,0), 
	"NM_HOST" VARCHAR2(100 BYTE), 
	"DS_CONEXAO" VARCHAR2(100 BYTE), 
	"DS_PAGINA" VARCHAR2(100 BYTE), 
	"DT_ERRO" TIMESTAMP (6), 
	"DS_EXCECAO" VARCHAR2(500 BYTE), 
	"DS_ERRO" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" 
 LOB ("DS_ERRO") STORE AS BASICFILE (
  TABLESPACE "PANDORA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ESQUEMA
--------------------------------------------------------

  CREATE TABLE "PANDORA"."ESQUEMA" 
   (	"ID" NUMBER, 
	"ID_SERVICO" NUMBER, 
	"NM_ESQUEMA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table FUNCIONALIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."FUNCIONALIDADE" 
   (	"ID" NUMBER, 
	"DS_FUNCIONALIDADE" VARCHAR2(50 BYTE), 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
  
  GRANT SELECT ON "PANDORA"."FUNCIONALIDADE" TO "BLANK";
  GRANT SELECT ON "PANDORA"."FUNCIONALIDADE" TO "CONECTA";
  GRANT SELECT ON "PANDORA"."FUNCIONALIDADE" TO "URNAS";
  GRANT SELECT ON "PANDORA"."FUNCIONALIDADE" TO "DIPLOMAS";
--------------------------------------------------------
--  DDL for Table FUNCIONALIDADE_TIPO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."FUNCIONALIDADE_TIPO" 
   (	"ID_FUNCIONALIDADE" NUMBER, 
	"ID_TIPO_FUNCIONALIDADE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."GRUPO" 
   (	"ID" NUMBER, 
	"DS_GRUPO" VARCHAR2(50 BYTE), 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table GRUPO_VW_UNIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."GRUPO_VW_UNIDADE" 
   (	"ID_GRUPO" NUMBER, 
	"ID_VW_UNIDADE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table GRUPO_VW_USUARIO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."GRUPO_VW_USUARIO" 
   (	"ID_GRUPO" NUMBER, 
	"NR_MATRICULA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table HOST
--------------------------------------------------------

  CREATE TABLE "PANDORA"."HOST" 
   (	"ID" NUMBER, 
	"NM_HOST" VARCHAR2(100 BYTE), 
	"TP_HOST" NUMBER(2,0), 
	"DS_FINALIDADE" VARCHAR2(4000 BYTE), 
	"IP_HOST" VARCHAR2(30 BYTE), 
	"FG_VIRTUAL" NUMBER(1,0), 
	"ID_HOST_PAI" NUMBER, 
	"DS_OBSERVACAO" VARCHAR2(4000 BYTE), 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table INSTALACAO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."INSTALACAO" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"ID_HOST" NUMBER, 
	"ID_SERVICO" NUMBER, 
	"ID_ESQUEMA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table LINK
--------------------------------------------------------

  CREATE TABLE "PANDORA"."LINK" 
   (	"ID" NUMBER, 
	"DS_TITULO" VARCHAR2(255 BYTE), 
	"DS_URL" VARCHAR2(1000 BYTE), 
	"DT_CRIACAO" DATE, 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE "PANDORA"."LOG" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"DS_FUNCIONALIDADE" NUMBER(5,0), 
	"TP_LOG" VARCHAR2(500 BYTE), 
	"NM_LOGIN" VARCHAR2(20 BYTE), 
	"NR_MATRICULA" VARCHAR2(8 BYTE), 
	"ID_UNIDADE" NUMBER(5,0), 
	"DT_LOG" TIMESTAMP (6), 
	"DS_LOG" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" 
 LOB ("DS_LOG") STORE AS BASICFILE (
  TABLESPACE "PANDORA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table NOTICIA
--------------------------------------------------------

  CREATE TABLE "PANDORA"."NOTICIA" 
   (	"ID" NUMBER, 
	"DS_TITULO" VARCHAR2(255 BYTE), 
	"DS_NOTICIA" VARCHAR2(2000 BYTE), 
	"DT_CRIACAO" DATE, 
	"FG_ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table PARAMETRO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PARAMETRO" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"DS_URL_SEGURANCA_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_ENTIDADE_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_LOG_TRE" VARCHAR2(1000 BYTE), 
	"DS_URL_EMAIL_TRE" VARCHAR2(1000 BYTE), 
	"NR_LIMITE_USUARIO" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table PARAMETRO_VW_UNIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PARAMETRO_VW_UNIDADE" 
   (	"ID_PARAMETRO" NUMBER, 
	"ID_VW_UNIDADE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table PERFIL
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL" 
   (	"ID" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"DS_PERFIL" VARCHAR2(50 BYTE), 
	"FG_ATIVO" NUMBER(1,0), 
	"FG_PADRAO" NUMBER(1,0), 
	"FG_LOTACAO_USUARIO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
  
  GRANT SELECT ON "PANDORA"."PERFIL" TO "BLANK";
  GRANT SELECT ON "PANDORA"."PERFIL" TO "CONECTA";
  GRANT SELECT ON "PANDORA"."PERFIL" TO "URNAS";
  GRANT SELECT ON "PANDORA"."PERFIL" TO "DIPLOMAS";
--------------------------------------------------------
--  DDL for Table PERFIL_FUNCIONALIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" 
   (	"ID_PERFIL" NUMBER, 
	"ID_FUNCIONALIDADE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
  
  GRANT SELECT ON "PANDORA"."PERFIL_FUNCIONALIDADE" TO "BLANK";
  GRANT SELECT ON "PANDORA"."PERFIL_FUNCIONALIDADE" TO "CONECTA";
  GRANT SELECT ON "PANDORA"."PERFIL_FUNCIONALIDADE" TO "URNAS";
  GRANT SELECT ON "PANDORA"."PERFIL_FUNCIONALIDADE" TO "DIPLOMAS";
--------------------------------------------------------
--  DDL for Table PERFIL_GRUPO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL_GRUPO" 
   (	"ID_PERFIL" NUMBER, 
	"ID_GRUPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table PERFIL_VW_UNIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL_VW_UNIDADE" 
   (	"ID_PERFIL" NUMBER, 
	"ID_VW_UNIDADE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table PERFIL_VW_UNIDADE_DADOS
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL_VW_UNIDADE_DADOS" 
   (	"ID_PERFIL" NUMBER, 
	"ID_VW_UNIDADE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
  
  GRANT SELECT ON "PANDORA"."PERFIL_VW_UNIDADE_DADOS" TO "BLANK";
  GRANT SELECT ON "PANDORA"."PERFIL_VW_UNIDADE_DADOS" TO "CONECTA";
  GRANT SELECT ON "PANDORA"."PERFIL_VW_UNIDADE_DADOS" TO "URNAS";
  GRANT SELECT ON "PANDORA"."PERFIL_VW_UNIDADE_DADOS" TO "DIPLOMAS";
--------------------------------------------------------
--  DDL for Table PERFIL_VW_USUARIO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."PERFIL_VW_USUARIO" 
   (	"ID_PERFIL" NUMBER, 
	"NR_MATRICULA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table SERVICO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."SERVICO" 
   (	"ID" NUMBER, 
	"ID_HOST" NUMBER, 
	"NM_SERVICO" VARCHAR2(100 BYTE), 
	"NR_PORTA" NUMBER(5,0), 
	"TP_SERVICO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table SISTEMA
--------------------------------------------------------

  CREATE TABLE "PANDORA"."SISTEMA" 
   (	"ID" NUMBER, 
	"SG_SISTEMA" VARCHAR2(50 BYTE), 
	"NM_SISTEMA" VARCHAR2(200 BYTE), 
	"TP_CLASSIFICACAO" VARCHAR2(1 BYTE), 
	"DS_FINALIDADE" VARCHAR2(4000 BYTE), 
	"TP_FASE" NUMBER(2,0), 
	"DS_ORIGEM" VARCHAR2(100 BYTE), 
	"FG_ODIN" NUMBER(1,0), 
	"TP_ACESSO" NUMBER(2,0), 
	"FG_ATIVO" NUMBER(1,0), 
	"ID_UNIDADE_GESTORA" NUMBER(5,0), 
	"ID_GESTOR_ACESSO" NUMBER(5,0), 
	"ID_GESTOR_TECNICO" NUMBER(5,0), 
	"DS_LINK_ACESSO" VARCHAR2(500 BYTE), 
	"DS_LINK_CODIGO_FONTE" VARCHAR2(500 BYTE), 
	"DS_LINK_DOCUMENTACAO" VARCHAR2(500 BYTE), 
	"DS_OBSERVACAO" VARCHAR2(4000 BYTE), 
	"FG_LOTACAO_USUARIO" NUMBER(1,0), 
	"FG_ESSENCIAL_ELEICAO" NUMBER(1,0), 
	"SG_VISAO_EXTERNA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;

   COMMENT ON COLUMN "PANDORA"."SISTEMA"."FG_ESSENCIAL_ELEICAO" IS 'Indica se este sistema é essencial durante o período eleitoral e deve e/ou pode ficar ativo';
   COMMENT ON COLUMN "PANDORA"."SISTEMA"."SG_VISAO_EXTERNA" IS 'Sigla identificadora para outros sistemas/schemas que disponibilizarão informações para este. Os objetos a serem disponibilizados utilizarão esta sigla para identificação do destino. ';
   GRANT SELECT ON "PANDORA"."SISTEMA" TO "BLANK";
   GRANT SELECT ON "PANDORA"."SISTEMA" TO "CONECTA";
   GRANT SELECT ON "PANDORA"."SISTEMA" TO "URNAS";
   GRANT SELECT ON "PANDORA"."SISTEMA" TO "DIPLOMAS";
--------------------------------------------------------
--  DDL for Table SISTEMA_TECNOLOGIA
--------------------------------------------------------

  CREATE TABLE "PANDORA"."SISTEMA_TECNOLOGIA" 
   (	"ID_SISTEMA" NUMBER, 
	"ID_TECNOLOGIA_SISTEMA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table SISTEMA_VW_USUARIO
--------------------------------------------------------

  CREATE TABLE "PANDORA"."SISTEMA_VW_USUARIO" 
   (	"ID_SISTEMA" NUMBER, 
	"NR_MATRICULA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table TECNOLOGIA_SISTEMA
--------------------------------------------------------

  CREATE TABLE "PANDORA"."TECNOLOGIA_SISTEMA" 
   (	"ID" NUMBER, 
	"DS_TECNOLOGIA_SISTEMA" VARCHAR2(30 BYTE), 
	"TP_TECNOLOGIA_SISTEMA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Table TIPO_FUNCIONALIDADE
--------------------------------------------------------

  CREATE TABLE "PANDORA"."TIPO_FUNCIONALIDADE" 
   (	"ID" NUMBER, 
	"DS_TIPO_FUNCIONALIDADE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for View VW_FUNCIONALIDADE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PANDORA"."VW_FUNCIONALIDADE" ("ID_SISTEMA", "DS_PERFIL", "ID_FUNCIONALIDADE", "DS_FUNCIONALIDADE", "FG_ATIVO") AS 
  select p.id_sistema, p.ds_perfil, f.id, f.ds_funcionalidade, f.fg_ativo
  from perfil p, perfil_funcionalidade pf, funcionalidade f
where p.id = pf.id_perfil and f.id = pf.id_funcionalidade
;
--------------------------------------------------------
--  DDL for View VW_PERFIL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PANDORA"."VW_PERFIL" ("ID_SISTEMA", "NR_MATRICULA", "ID_VW_UNIDADE", "DS_PERFIL", "FG_ATIVO") AS 
  select s.id as id_sistema, vwu.matricula as nr_matricula, null as id_vw_unidade, p.ds_perfil, p.fg_ativo
from perfil p, sistema s, perfil_vw_usuario pvwu, dados_corporativos.vw_usuario vwu
where p.id_sistema = s.id and
      (p.id = pvwu.id_perfil and pvwu.nr_matricula = vwu.matricula)
union
select s.id as id_sistema, null as nr_matricula, vwu.id_unidade, p.ds_perfil, p.fg_ativo
from perfil p, sistema s, perfil_vw_unidade pvwu, dados_corporativos.vw_unidade vwu
where p.id_sistema = s.id and
      (p.id = pvwu.id_perfil and pvwu.id_vw_unidade = vwu.id_unidade)
union
select s.id as id_sistema, gd.nr_matricula, gd.id_vw_unidade, p.ds_perfil, p.fg_ativo
from perfil p, sistema s, perfil_grupo pg,
      (select g.id as id_grupo, gvwu.nr_matricula, null as id_vw_unidade
       from grupo g, grupo_vw_usuario gvwu
       where g.id = gvwu.id_grupo and g.fg_ativo = 1
       union all
       select g.id as id_grupo, null as nr_matricula, gvwu.id_vw_unidade
       from grupo g, grupo_vw_unidade gvwu
       where g.id = gvwu.id_grupo and g.fg_ativo = 1) gd
where p.id_sistema = s.id and
      (p.id = pg.id_perfil and pg.id_grupo = gd.id_grupo)
;
--------------------------------------------------------
--  DDL for Index UK_HOST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."UK_HOST" ON "PANDORA"."HOST" ("NM_HOST", "TP_HOST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_FUNCIONALIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_FUNCIONALIDADE" ON "PANDORA"."FUNCIONALIDADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_NOTICIA" ON "PANDORA"."NOTICIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL_VW_UNIDADE_DADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL_VW_UNIDADE_DADOS" ON "PANDORA"."PERFIL_VW_UNIDADE_DADOS" ("ID_PERFIL", "ID_VW_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL_GRUPO" ON "PANDORA"."PERFIL_GRUPO" ("ID_PERFIL", "ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_INSTALACAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_INSTALACAO" ON "PANDORA"."INSTALACAO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO_VW_UNIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_GRUPO_VW_UNIDADE" ON "PANDORA"."GRUPO_VW_UNIDADE" ("ID_GRUPO", "ID_VW_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_LINK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_LINK" ON "PANDORA"."LINK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_FUNCIONALIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_TIPO_FUNCIONALIDADE" ON "PANDORA"."TIPO_FUNCIONALIDADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO_VW_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_GRUPO_VW_USUARIO" ON "PANDORA"."GRUPO_VW_USUARIO" ("ID_GRUPO", "NR_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index UK_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."UK_PERFIL" ON "PANDORA"."PERFIL" ("ID_SISTEMA", "DS_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_SERVICO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_SERVICO" ON "PANDORA"."SERVICO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_GRUPO" ON "PANDORA"."GRUPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_SISTEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_SISTEMA" ON "PANDORA"."SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_SISTEMA_TECNOLOGIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_SISTEMA_TECNOLOGIA" ON "PANDORA"."SISTEMA_TECNOLOGIA" ("ID_SISTEMA", "ID_TECNOLOGIA_SISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL_FUNCIONALIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL_FUNCIONALIDADE" ON "PANDORA"."PERFIL_FUNCIONALIDADE" ("ID_PERFIL", "ID_FUNCIONALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index UK_FUNCIONALIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."UK_FUNCIONALIDADE" ON "PANDORA"."FUNCIONALIDADE" ("DS_FUNCIONALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_ERRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_ERRO" ON "PANDORA"."ERRO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL_VW_UNIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL_VW_UNIDADE" ON "PANDORA"."PERFIL_VW_UNIDADE" ("ID_PERFIL", "ID_VW_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_TECNOLOGIA_SISTEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_TECNOLOGIA_SISTEMA" ON "PANDORA"."TECNOLOGIA_SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_LOG" ON "PANDORA"."LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_FUNCIONALIDADE_TIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_FUNCIONALIDADE_TIPO" ON "PANDORA"."FUNCIONALIDADE_TIPO" ("ID_FUNCIONALIDADE", "ID_TIPO_FUNCIONALIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index UK_GRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."UK_GRUPO" ON "PANDORA"."GRUPO" ("DS_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL" ON "PANDORA"."PERFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PARAMETRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PARAMETRO" ON "PANDORA"."PARAMETRO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_ESQUEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_ESQUEMA" ON "PANDORA"."ESQUEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PARAMETRO_VW_UNIDADE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PARAMETRO_VW_UNIDADE" ON "PANDORA"."PARAMETRO_VW_UNIDADE" ("ID_PARAMETRO", "ID_VW_UNIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_PERFIL_VW_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_PERFIL_VW_USUARIO" ON "PANDORA"."PERFIL_VW_USUARIO" ("ID_PERFIL", "NR_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index UK_SISTEMA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."UK_SISTEMA" ON "PANDORA"."SISTEMA" ("SG_SISTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_HOST
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_HOST" ON "PANDORA"."HOST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Index PK_SISTEMA_VW_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PANDORA"."PK_SISTEMA_VW_USUARIO" ON "PANDORA"."SISTEMA_VW_USUARIO" ("ID_SISTEMA", "NR_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA" ;
--------------------------------------------------------
--  DDL for Procedure PC_ADMINISTRAR_VW_UNIDADE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PANDORA"."PC_ADMINISTRAR_VW_UNIDADE" 
(A_IDS_VW_UNIDADE in AR_ID_NUMBER) as
begin
declare
  cursor PERFIL is select * from PERFIL P;
  RG_PERFIL PERFIL%ROWTYPE;

  ID_PARAMETRO NUMBER;

  NR_CONTADOR_PERFIL NUMBER;

begin
  -- exclui unidade.
  delete from PARAMETRO_VW_UNIDADE;

  -- inclui unidade.
  select P.ID into ID_PARAMETRO from PARAMETRO P;
  for I in A_IDS_VW_UNIDADE.first..A_IDS_VW_UNIDADE.last loop
    insert into PARAMETRO_VW_UNIDADE values (ID_PARAMETRO, A_IDS_VW_UNIDADE(I));
  end loop;

  -- atualiza perfil.
  open PERFIL;
  loop
    fetch PERFIL into RG_PERFIL;
    exit when PERFIL%NOTFOUND;

    for I in A_IDS_VW_UNIDADE.first..A_IDS_VW_UNIDADE.last loop
      select count(*) into NR_CONTADOR_PERFIL from PERFIL_VW_UNIDADE PVWU where PVWU.ID_PERFIL = RG_PERFIL.ID and PVWU.ID_VW_UNIDADE = A_IDS_VW_UNIDADE(I);
      if NR_CONTADOR_PERFIL = 0 then
        insert into PERFIL_VW_UNIDADE values (RG_PERFIL.ID, A_IDS_VW_UNIDADE(I));
      end if;
    end loop;
  end loop;
  close PERFIL;

  commit;
end;

end PC_ADMINISTRAR_VW_UNIDADE;

/
--------------------------------------------------------
--  DDL for Function FC_VERIFICAR_IDS_NUMBER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PANDORA"."FC_VERIFICAR_IDS_NUMBER" 
(A_ID_CONTROLE in number, A_IDS_NUMBER in AR_ID_NUMBER, A_TP_CONTROLE in number) return varchar2 is
  -- objetivo: verifica se id pertence a todos os ids informados  
  --     
  -- A_ID_CONTROLE - código de controle
  -- A_IDS_NUMBER - ids a buscar (todos simultaneamente)
  -- A_TP_CONTROLE - tipo de controle
  -- retorno: 'S/N'

  NR_TAMANHO_ARRAY number;
  NR_CONTADOR_CONTROLE number;
begin
  NR_TAMANHO_ARRAY := A_IDS_NUMBER.count;

  if A_TP_CONTROLE = 0 then
    select count(*) into NR_CONTADOR_CONTROLE from SERVICO S where S.ID_HOST = A_ID_CONTROLE and S.ID member of A_IDS_NUMBER;
  elsif A_TP_CONTROLE = 1 then
    select count(*) into NR_CONTADOR_CONTROLE from ESQUEMA E where E.ID_SERVICO = A_ID_CONTROLE and E.ID member of A_IDS_NUMBER;
  elsif A_TP_CONTROLE = 2 then
    select count(*) into NR_CONTADOR_CONTROLE from INSTALACAO I where I.ID_SISTEMA = A_ID_CONTROLE and I.ID_HOST member of A_IDS_NUMBER;
  elsif A_TP_CONTROLE = 3 then
    select count(*) into NR_CONTADOR_CONTROLE from INSTALACAO I where I.ID_SISTEMA = A_ID_CONTROLE and I.ID_SERVICO member of A_IDS_NUMBER;    
  elsif A_TP_CONTROLE = 4 then
    select count(*) into NR_CONTADOR_CONTROLE from INSTALACAO I where I.ID_SISTEMA = A_ID_CONTROLE and I.ID_ESQUEMA member of A_IDS_NUMBER;    
  else
    select count(*) into NR_CONTADOR_CONTROLE from FUNCIONALIDADE_TIPO FT where FT.ID_FUNCIONALIDADE = A_ID_CONTROLE and FT.ID_TIPO_FUNCIONALIDADE member of A_IDS_NUMBER;
  end if;

  if NR_CONTADOR_CONTROLE < NR_TAMANHO_ARRAY then
    return 'N';
  else
    return 'S';
  end if;

exception
  when others then
    return 'N';
end;

/
--------------------------------------------------------
--  DDL for Function FC_VERIFICAR_IDS_STRING
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PANDORA"."FC_VERIFICAR_IDS_STRING" 
(A_ID_CONTROLE in number, A_IDS_STRING in AR_ID_STRING) return varchar2 is
  -- objetivo: verifica se id pertence a todos os ids informados  
  --     
  -- A_ID_CONTROLE - código de controle
  -- A_IDS_NUMBER - ids a buscar (todos simultaneamente)
  -- retorno: 'S/N'

  NR_TAMANHO_ARRAY number;
  NR_CONTADOR_CONTROLE number;
begin
  NR_TAMANHO_ARRAY := A_IDS_STRING.count;

  select count(*) into NR_CONTADOR_CONTROLE from SISTEMA_VW_USUARIO SVWU where SVWU.ID_SISTEMA = A_ID_CONTROLE and SVWU.NR_MATRICULA member of A_IDS_STRING;

  if NR_CONTADOR_CONTROLE < NR_TAMANHO_ARRAY then
    return 'N';
  else
    return 'S';
  end if;

exception
  when others then
    return 'N';
end;

/
--------------------------------------------------------
--  Constraints for Table INSTALACAO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."INSTALACAO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."INSTALACAO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."INSTALACAO" MODIFY ("ID_HOST" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."INSTALACAO" MODIFY ("ID_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."INSTALACAO" ADD CONSTRAINT "PK_INSTALACAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCIONALIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."FUNCIONALIDADE" ADD CONSTRAINT "PK_FUNCIONALIDADE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."FUNCIONALIDADE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."FUNCIONALIDADE" MODIFY ("DS_FUNCIONALIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESQUEMA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."ESQUEMA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ESQUEMA" MODIFY ("ID_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ESQUEMA" MODIFY ("NM_ESQUEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ESQUEMA" ADD CONSTRAINT "PK_ESQUEMA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TECNOLOGIA_SISTEMA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."TECNOLOGIA_SISTEMA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."TECNOLOGIA_SISTEMA" MODIFY ("DS_TECNOLOGIA_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."TECNOLOGIA_SISTEMA" MODIFY ("TP_TECNOLOGIA_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."TECNOLOGIA_SISTEMA" ADD CONSTRAINT "PK_TECNOLOGIA_SISTEMA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERFIL_VW_UNIDADE_DADOS
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE_DADOS" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE_DADOS" MODIFY ("ID_VW_UNIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE_DADOS" ADD CONSTRAINT "PK_PERFIL_VW_UNIDADE_DADOS" PRIMARY KEY ("ID_PERFIL", "ID_VW_UNIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SISTEMA_TECNOLOGIA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SISTEMA_TECNOLOGIA" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA_TECNOLOGIA" MODIFY ("ID_TECNOLOGIA_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA_TECNOLOGIA" ADD CONSTRAINT "PK_SISTEMA_TECNOLOGIA" PRIMARY KEY ("ID_SISTEMA", "ID_TECNOLOGIA_SISTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."GRUPO" ADD CONSTRAINT "PK_GRUPO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."GRUPO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."GRUPO" MODIFY ("DS_GRUPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARAMETRO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PARAMETRO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PARAMETRO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PARAMETRO" MODIFY ("NR_LIMITE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PARAMETRO" ADD CONSTRAINT "PK_PARAMETRO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARAMETRO_VW_UNIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PARAMETRO_VW_UNIDADE" MODIFY ("ID_PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PARAMETRO_VW_UNIDADE" MODIFY ("ID_VW_UNIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PARAMETRO_VW_UNIDADE" ADD CONSTRAINT "PK_PARAMETRO_VW_UNIDADE" PRIMARY KEY ("ID_PARAMETRO", "ID_VW_UNIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERFIL_FUNCIONALIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" MODIFY ("ID_FUNCIONALIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" ADD CONSTRAINT "PK_PERFIL_FUNCIONALIDADE" PRIMARY KEY ("ID_PERFIL", "ID_FUNCIONALIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ERRO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."ERRO" ADD CONSTRAINT "PK_ERRO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("NM_LOGIN" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("NR_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("ID_UNIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("NM_HOST" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("DS_CONEXAO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("DS_PAGINA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("DT_ERRO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."ERRO" MODIFY ("DS_EXCECAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "PANDORA"."LOG" ADD CONSTRAINT "PK_LOG" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."LOG" MODIFY ("NR_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("ID_UNIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("DT_LOG" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("TP_LOG" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LOG" MODIFY ("NM_LOGIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_USUARIO" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_USUARIO" MODIFY ("NR_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_USUARIO" ADD CONSTRAINT "PK_PERFIL_VW_USUARIO" PRIMARY KEY ("ID_PERFIL", "NR_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GRUPO_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."GRUPO_VW_USUARIO" ADD CONSTRAINT "PK_GRUPO_VW_USUARIO" PRIMARY KEY ("ID_GRUPO", "NR_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."GRUPO_VW_USUARIO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."GRUPO_VW_USUARIO" MODIFY ("NR_MATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPO_VW_UNIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."GRUPO_VW_UNIDADE" ADD CONSTRAINT "PK_GRUPO_VW_UNIDADE" PRIMARY KEY ("ID_GRUPO", "ID_VW_UNIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."GRUPO_VW_UNIDADE" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."GRUPO_VW_UNIDADE" MODIFY ("ID_VW_UNIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SISTEMA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SISTEMA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA" MODIFY ("SG_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA" MODIFY ("NM_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA" MODIFY ("TP_CLASSIFICACAO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA" MODIFY ("TP_FASE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA" ADD CONSTRAINT "CK_SISTEMA_CLASSIFICACAO" CHECK ("TP_CLASSIFICACAO"='A' OR "TP_CLASSIFICACAO"='J' OR "TP_CLASSIFICACAO"='E' OR "TP_CLASSIFICACAO"='T') ENABLE;
  ALTER TABLE "PANDORA"."SISTEMA" ADD CONSTRAINT "CK_SISTEMA_FASE" CHECK ("TP_FASE"=1 OR "TP_FASE"=2 OR "TP_FASE"=3 OR "TP_FASE"=4 OR "TP_FASE"=5 OR "TP_FASE"=6 OR "TP_FASE"=7) ENABLE;
  ALTER TABLE "PANDORA"."SISTEMA" ADD CONSTRAINT "CK_SISTEMA_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "PANDORA"."SISTEMA" ADD CONSTRAINT "PK_SISTEMA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."SISTEMA" ADD CONSTRAINT "UK_SISTEMA" UNIQUE ("SG_SISTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_FUNCIONALIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."TIPO_FUNCIONALIDADE" ADD CONSTRAINT "PK_TIPO_FUNCIONALIDADE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."TIPO_FUNCIONALIDADE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."TIPO_FUNCIONALIDADE" MODIFY ("DS_TIPO_FUNCIONALIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOMINIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."DOMINIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."DOMINIO" MODIFY ("TP_DOMINIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICIA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."NOTICIA" ADD CONSTRAINT "CK_NOTICIA_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "PANDORA"."NOTICIA" ADD CONSTRAINT "PK_NOTICIA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."NOTICIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."NOTICIA" MODIFY ("DS_TITULO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."NOTICIA" MODIFY ("DS_NOTICIA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."NOTICIA" MODIFY ("DT_CRIACAO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL" MODIFY ("DS_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL" ADD CONSTRAINT "PK_PERFIL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."PERFIL" ADD CONSTRAINT "UK_PERFIL" UNIQUE ("ID_SISTEMA", "DS_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERFIL_GRUPO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_GRUPO" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_GRUPO" ADD CONSTRAINT "PK_PERFIL_GRUPO" PRIMARY KEY ("ID_PERFIL", "ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCIONALIDADE_TIPO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."FUNCIONALIDADE_TIPO" ADD CONSTRAINT "PK_FUNCIONALIDADE_TIPO" PRIMARY KEY ("ID_FUNCIONALIDADE", "ID_TIPO_FUNCIONALIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
  ALTER TABLE "PANDORA"."FUNCIONALIDADE_TIPO" MODIFY ("ID_FUNCIONALIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."FUNCIONALIDADE_TIPO" MODIFY ("ID_TIPO_FUNCIONALIDADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOST
--------------------------------------------------------

  ALTER TABLE "PANDORA"."HOST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."HOST" MODIFY ("NM_HOST" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."HOST" MODIFY ("TP_HOST" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."HOST" ADD CONSTRAINT "CK_HOST_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "PANDORA"."HOST" ADD CONSTRAINT "CK_HOST_VIRTUAL" CHECK ("FG_VIRTUAL"=1 OR "FG_VIRTUAL"=0) ENABLE;
  ALTER TABLE "PANDORA"."HOST" ADD CONSTRAINT "PK_HOST" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SERVICO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SERVICO" MODIFY ("ID_HOST" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SERVICO" MODIFY ("NM_SERVICO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SERVICO" MODIFY ("NR_PORTA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SERVICO" ADD CONSTRAINT "PK_SERVICO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERFIL_VW_UNIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE" MODIFY ("ID_VW_UNIDADE" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE" ADD CONSTRAINT "PK_PERFIL_VW_UNIDADE" PRIMARY KEY ("ID_PERFIL", "ID_VW_UNIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SISTEMA_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SISTEMA_VW_USUARIO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA_VW_USUARIO" MODIFY ("NR_MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."SISTEMA_VW_USUARIO" ADD CONSTRAINT "PK_SISTEMA_VW_USUARIO" PRIMARY KEY ("ID_SISTEMA", "NR_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LINK
--------------------------------------------------------

  ALTER TABLE "PANDORA"."LINK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LINK" MODIFY ("DS_TITULO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LINK" MODIFY ("DS_URL" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LINK" MODIFY ("DT_CRIACAO" NOT NULL ENABLE);
  ALTER TABLE "PANDORA"."LINK" ADD CONSTRAINT "CK_LINK_ATIVO" CHECK ("FG_ATIVO"=1 OR "FG_ATIVO"=0) ENABLE;
  ALTER TABLE "PANDORA"."LINK" ADD CONSTRAINT "PK_LINK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PANDORA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ERRO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."ERRO" ADD CONSTRAINT "FK_ERRO_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESQUEMA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."ESQUEMA" ADD CONSTRAINT "FK_ESQUEMA_SERVICO" FOREIGN KEY ("ID_SERVICO")
	  REFERENCES "PANDORA"."SERVICO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNCIONALIDADE_TIPO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."FUNCIONALIDADE_TIPO" ADD CONSTRAINT "FK_FUNC_TIPO_FUNC" FOREIGN KEY ("ID_FUNCIONALIDADE")
	  REFERENCES "PANDORA"."FUNCIONALIDADE" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."FUNCIONALIDADE_TIPO" ADD CONSTRAINT "FK_FUNC_TIPO_TIPO_FUNC" FOREIGN KEY ("ID_TIPO_FUNCIONALIDADE")
	  REFERENCES "PANDORA"."TIPO_FUNCIONALIDADE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_VW_UNIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."GRUPO_VW_UNIDADE" ADD CONSTRAINT "FK_GRUPO_VW_UNIDADE_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PANDORA"."GRUPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."GRUPO_VW_USUARIO" ADD CONSTRAINT "FK_GRUPO_VW_USUARIO_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PANDORA"."GRUPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOST
--------------------------------------------------------

  ALTER TABLE "PANDORA"."HOST" ADD CONSTRAINT "FK_HOST_HOST" FOREIGN KEY ("ID_HOST_PAI")
	  REFERENCES "PANDORA"."HOST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSTALACAO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."INSTALACAO" ADD CONSTRAINT "FK_INSTALACAO_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."INSTALACAO" ADD CONSTRAINT "FK_INSTALACAO_HOST" FOREIGN KEY ("ID_HOST")
	  REFERENCES "PANDORA"."HOST" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."INSTALACAO" ADD CONSTRAINT "FK_INSTALACAO_SERVICO" FOREIGN KEY ("ID_SERVICO")
	  REFERENCES "PANDORA"."SERVICO" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."INSTALACAO" ADD CONSTRAINT "FK_INSTALACAO_ESQUEMA" FOREIGN KEY ("ID_ESQUEMA")
	  REFERENCES "PANDORA"."ESQUEMA" ("ID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "PANDORA"."LOG" ADD CONSTRAINT "FK_LOG_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL" ADD CONSTRAINT "FK_PERFIL_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_FUNCIONALIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" ADD CONSTRAINT "FK_PERFIL_FUNC_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "PANDORA"."PERFIL" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."PERFIL_FUNCIONALIDADE" ADD CONSTRAINT "FK_PERFIL_FUNC_FUNC" FOREIGN KEY ("ID_FUNCIONALIDADE")
	  REFERENCES "PANDORA"."FUNCIONALIDADE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_GRUPO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_GRUPO" ADD CONSTRAINT "FK_PERFIL_GRUPO_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "PANDORA"."PERFIL" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."PERFIL_GRUPO" ADD CONSTRAINT "FK_PERFIL_GRUPO_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "PANDORA"."GRUPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_VW_UNIDADE
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE" ADD CONSTRAINT "FK_PERFIL_VW_UNIDADE_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "PANDORA"."PERFIL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_VW_UNIDADE_DADOS
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_UNIDADE_DADOS" ADD CONSTRAINT "FK_PERFIL_VW_UNID_DDS_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "PANDORA"."PERFIL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERFIL_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."PERFIL_VW_USUARIO" ADD CONSTRAINT "FK_PERFIL_VW_USUARIO_PERFIL" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "PANDORA"."PERFIL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SERVICO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SERVICO" ADD CONSTRAINT "FK_SERVICO_HOST" FOREIGN KEY ("ID_HOST")
	  REFERENCES "PANDORA"."HOST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SISTEMA_TECNOLOGIA
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SISTEMA_TECNOLOGIA" ADD CONSTRAINT "FK_SISTEMA_TECNO_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
  ALTER TABLE "PANDORA"."SISTEMA_TECNOLOGIA" ADD CONSTRAINT "FK_SISTEMA_TECNO_TECNO_SISTEMA" FOREIGN KEY ("ID_TECNOLOGIA_SISTEMA")
	  REFERENCES "PANDORA"."TECNOLOGIA_SISTEMA" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SISTEMA_VW_USUARIO
--------------------------------------------------------

  ALTER TABLE "PANDORA"."SISTEMA_VW_USUARIO" ADD CONSTRAINT "FK_SISTEMA_VW_USUARIO_SISTEMA" FOREIGN KEY ("ID_SISTEMA")
	  REFERENCES "PANDORA"."SISTEMA" ("ID") ENABLE;
